desc 'pod私有库自动化更新升级'
lane :RMPodAutoUpgrageTool do |options|

#git commit时的message
logMessage = options[:message]
#tag值
tagNum = options[:tag]
#当前私有库spec文件名称
podspecName = options[:specName]

# 航道上需要执行的操作
# 这里的路径以仓库根目录为准

# 1、修改spec文件（修改s.version，s.description等）
# 2、pod install （使Example与pod下来的库产生关联）
cocoapods(
  clean: true,
  podfile: "./Example/Podfile"
)


# 3、提交本地仓库代码至远程仓库
git_add(path: ".")
git_commit(path: ".", message: logMessage)
push_to_git_remote


# 4、打标签，并提交至远程
# 先验证tag是否存在，如果存在则删除本地标签和远程标签
if git_tag_exists(tag: tagNum)
  UI.message("您输入的tag:#{tagNum}已存在，即将自动清除") 
  remove_git_tag(tagNum: tagNum)
end
add_git_tag(
  tag: tagNum
)
push_git_tags


# 5、验证spec，并提至私有索引库
pod_lib_lint(allow_warnings: true, use_libraries: true)

# 6、spec推到远端，这里podspec的名字需要由外界传入，repo可以直接写死
pod_push(path: "#{podspecName}.podspec", repo: "rm-ios-spec", allow_warnings: true, use_libraries: true)


end
